### ISSUE TITLE
cannot add custom formats

### ISSUE THREAD

**Issue by gcloeval** [Download/ulog#13]
Hi, this libraray looks like exactly what I need.
I am trying to add a custom format, but it fails with "Cannot read property 'push' of undefined"

It is with the latest best, I have put a codesandbox here:
https://codesandbox.io/s/731lrno381

If you uncomment the line:
// appLog.formats.push(myFormat);
it will show the exception.

Also not really important for me, but I noticed that TRACE level wasnt showing up when.

Let me know if you have some idea about the formatter, I just want to be able to do exactly what your example shows - prefix the message with the module-name i.e. main-app or component-XYZ.

**Comment by Download** [comment]
Hi @gcloeval 

Sorry for the late response I was away this weekend.
About your questions, have a look at my modified version of your example:
https://codesandbox.io/s/6y7qw945rk

As for the formatter: I changed the code to push to `ulog.formats`. 
Your issue has made me think. As of this moment, formatters are global to all loggers. It might be better if formatters where more like levels; a global option that could be overridden for individual loggers.
It is good you are testing now that v2 is still in beta. You can help me improve upon it. Thanks!

As for the TRACE messages not showing up. If you are using Chrome, be aware it does not show all log message by default. Chrome actually implements level filtering of it's own and by default Verbose messages are not included. Make sure to enable that in the filter options on the Console tab.

Thanks for trying out ulog and please leave more issues if you have more questions.

**Comment by Download** [comment]
I will prepare a new version with some improvements in the coming weeks. I'll ping you when it's published.

**Comment by gcloeval** [comment]
Hey thanks for the fix.
This is more than enough functionallity for me, but I also agree - it could be useful if formatters could be overriten per module. 
That way, I could quickly eye-scan interesting modules by just appending few ----- to the formatter, i.e. for example, given a log statements stream like this:

"redux - Now dispatching getist action"
"middleware - Authenticating user"
"redux - Processing result X"
"user list component" - received data
"user list component" - updating object
"redux" - Now dispatching update user"
....

if formatters can be changed per module, i can quickly for ex. tweak redux module with a few ---------, it will make it easier to eye-scan and focus quickly, if it looked like this:

"redux ------------------------ Now dispatching getist action"
"middleware - Authenticating user"
"redux ------------------------ Processing result X"
"user list component" - received data
"user list component" - updating object
"redux ------------------------ Now dispatching update user"

then when i need to focus back on another layer/component/module, i quickly switch the formats.

but like I said, even as it is right now is sufficient for me. 

I will let you know if I get any other ideas, I am also busy for a bit so had to put the side project where I use this on hold for a bit.

anyways, thanks for the library

**Comment by szerintedmi** [comment]
Thanks for the module, simple, small, like it :)
My 2cents on this from your example:
```
appLog.error("This one does not :(");
// I am actually doubting whether this is
// a great feature...
// it grew because of the desire to not mess
// with the line numbers in the stack trace
// but I think it is better if the formatting
// is always applied if formatters are added
```

I'm not sure about the line numbers issue but I agree formatting applied to `ulog.log`, `.error` etc. would be nice

**Comment by Download** [comment]
@szerintedmi Yes, will be implemented in v2
See #15
