### ISSUE TITLE
Fix formatting

### ISSUE THREAD

**Issue by Download** [Download/ulog#16]
Either don't apply formatting, or do, but the current hybrid design is confusing.

If the inheritable `formats` property is empty, don't apply any formatting and leave line numbers intact
If there are formats configured, make sure all log methods use these formats.

**Comment by Download** [comment]
See #15 #13

**Comment by Vadorequest** [comment]
I agree, the current design is confusing. I thought formats didn't work, until I understood I shouldn't use a method like `logger.info()` but `logger()` instead.

**Comment by Download** [comment]
See #15
