### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by MikeMitterer** [Download/ulog#19]
Please add TS definitions to your module

**Comment by Download** [comment]
Can you help me with a PR please?

**Comment by Download** [comment]
@MikeMitterer 
How much do you know about Typescript?

I am working on v2 of ulog and it will be using a new concept. It will be the first native implementation of [anylogger](https://npmjs.com/package/anylogger). The idea behind `anylogger` is to build the most lightweight logging shim I can and then use it as a logging facade. This way libraries can use `anylogger` to do logging and in the application you can select the logging framework and all libraries will start to use it automatically:

*my-lib.js*
```js
var log = require('anylogger')('my-lib')
log('logging is easy!')
```

In application code, you require (the adapter for) your logging framework:

```js
var ulog = require('ulog') // ulog has native anylogger support, no adapter needed :)
var log = ('anylogger')('app')
log('test') 
// no output shows as default level is info and this message is logged at log

// enable debug mode for all loggers
ulog.enable('*')
log('test 2') 
// > "test 2"

// ulog is now also being used by my-lib
require('my-lib') 
// > "logging is easy!"
```

As you can see, `anylogger` would be a simple logging facade for libraries to use. So it would be very useful for it to have Typescript definitions I think. But I never worked with Typescript and I am not sure how to make such files. Would you care to take a look at the [anylogger](https://npmjs.com/package/anylogger) project? v2 of `ulog` will be relying on `anylogger` so if you make a typescript definition for that one ulog will also benefit from it.

**Comment by Download** [comment]
See #14
