### ISSUE TITLE
'Cannot redefine property: name' error on android KitKat WebView

### ISSUE THREAD

**Issue by johnd0e** [Download/ulog#24]
https://github.com/Download/ulog/blob/fc5a47e5508342dd8e625da80cd3f61036802faf/ulog.js#L40

It's obvious that KitKat webview is based on some old webkit version.
Still it's not clear what exactly is the cause of this issue.

**Comment by Download** [comment]
Yeah it is mysterious, but I think I have solved it in later anylogger version
I will try to get around to fixing it here by updating dependencies

**Comment by johnd0e** [comment]
As I understand `ulog.umd.js` is built without using any dependency.
But it causes same error.

**Comment by Download** [comment]
@johnd0e 
Yes it is at the moment...
This lib (or at least version 2 of it) is still in flux quitte a bit, I'm sorry.
I recommend to stay on v1 for now, or try `anylogger`.
In v2 of ulog, the recommendation for client code (code just *using* the logger) will be to use only `anylogger`, like this:

```js
import anylogger from `anylogger`
const log = anylogger('my-app')
log('Hello, World')
```

Then in the main application entry point, include `ulog` just once:

```js
import ulog from `ulog`
// done. ulog in now acting as the logging framework for anylogger
import anylogger from `anylogger`
const log = anylogger('test')
log.debug('no output, because we are using ulog')
ulog.enable('test')
log.debug('output, because we enabled logger "test"')
```

So if you use anylogger now for your client code (possibly i.c.w. `debug` or `loglevel` for now) you will be able to drop in ulog v2 when the next beta is released.

**Comment by johnd0e** [comment]
> I recommend to stay on v1 for now, or try `anylogger`.

v1 has the same issue.

**Comment by Download** [comment]
@johnd0e 
Latest beta version of `ulog` I basically created just for you:
https://github.com/Download/ulog/commit/423ce1c6dc1c8c2a2ecae13e6dbb99308e301eba#diff-376aee9128f6965dd8f0dafec44349b6R49
It is on NPM as 2.0.0-beta.7:
https://www.npmjs.com/package/ulog/v/2.0.0-beta.7

Could you be a doll and try it out for me and let me know whether it fixed your issue?

**Comment by johnd0e** [comment]
Yet, all seems fine now, thanks!
