### ISSUE TITLE
License motivations - CC-BY

### ISSUE THREAD

**Issue by Vadorequest** [Download/ulog#28]
Why use such license? I'm wondering about your motivations. (it's not very well suited for software)

Why not MIT or similar?

![image](https://user-images.githubusercontent.com/3807458/82225946-26623a00-9926-11ea-8ef3-a16cc6cb2a50.png)

**Comment by Download** [comment]
It is the only license I could find that is totally free but does require attribution.
I don't think the 'Not recommended for software' remark was there when I chose it all those years ago...
I have been reconsidering though... my latest project, [anylogger](https://github.com/download/anylogger) is MIT licensed.
Can you give your thoughts? Would MIT be better?

**Comment by Vadorequest** [comment]
It's just more usual/common. I usually use MIT myself.
CCA 4.0 is rather rare, and makes wonder about "why".

**Comment by Download** [comment]
@Vadorequest 
It will be so!
