### ISSUE TITLE
How to set output to a file?

### ISSUE THREAD

**Issue by taoqf** [Download/ulog#34]
I could not find any clue about setting of log_output to a file in readme, is there an example?

**Comment by Download** [comment]
You can set outputs, but there is no file output yet. 

You can easily make a custom output like so:

```js
var customOutput = {
  log: function() {
    // this function will be called for 'log' level messages,
    // or for any levels for which no specific function exists
    // here you can write to file, send to network etc...
  },
  info: function() {
    // for info messages this function will be called.
    // for other levels, the like named function will be called, 
    // or `log` when no like named function exists
  }
}
```

Then, create a mod that adds this output to `ulog`:

```js
var ulog = require('ulog')
var outputs = require('ulog/mods/outputs')
ulog.use({
  use: [ outputs ],
  outputs: {
    custom: customOutput
  }
})
```

Then, set the `output` option for a logger to your custom output and it will start to use it.

I haven't yet come up with a mechanism to pass parameters to an output... Either we modify the output option so it can accept parameters (e.g. `log_output=custom(with:parameters)` or something), or maybe it's easier to make new settings. That's already easy to do. Expanding on the previous example, we could add an `output_file` setting and property to all loggers in the custom mod, like this:

```js
var ulog = require('ulog')
var outputs = require('ulog/mods/outputs')
var props = require('ulog/mods/props')
ulog.use({
  use: [ outputs, props ],
  outputs: {
    custom: customOutput
  },
  settings: {
    output_file: {
      prop: {
        default: './log.txt'
      }
    }
  }
})
```

I am planning on implementing a file output at some point, but if you are willing to invest some time on it we could maybe do it together. I will help you and make sure I release a version with the `file` output you made in it quickly. 

To get a better understanding of how outputs work, have a look at [the source of the `outputs` mod](https://github.com/Download/ulog/blob/master/mods/outputs/index.js). It contains 2 outputs by default, `console` and `drain`, where drain is basically just a noop:

```js
outputs: {
    drain: { log: function(){} },
    console: typeof console !== 'undefined' && console,
  }
```

As you can see it's really pretty simple. Any object that looks like a console can be a custom output and only the `log` function is required.

**Comment by Download** [comment]
Oh also maybe useful: You can change the output at runtime already. That part works. So to experiment with changing the output, change the setting for `log_output` to `drain` and watch how no messages get logged anymore. Or change the setting for `log_drain` to e.g. `console` and see how all messages now get logged. Basically any message within the active level gets sent to `log_output` and any message that's outside the active level gets send to `log_drain`.

**Comment by taoqf** [comment]
Thanks.
