### ISSUE TITLE
log.config file not processed correctly on change

### ISSUE THREAD

**Issue by Download** [Download/ulog#46]
Gets into an infinite loop sometimes...

**Comment by MikeM2343** [comment]
I just started using ulog and it is exactly what I'm looking for. Thank you!
I can confirm that I'm seeing the same issue on version 2.0.0-beta.15 every time I change log.config.
Let me know if you need more info

**Comment by Download** [comment]
I have gotten a bit sidetracked working on a [tutorial](https://ulog.js.org/tutorial/index.html). Will get back to fixing this issue soon!

**Comment by Download** [comment]
Didn't mean to close it right away. Let me first verify that this is indeed fixed.

**Comment by Download** [comment]
I think it is indeed fixed in [2.0.0-beta.18](https://github.com/Download/ulog/releases/tag/2.0.0-beta.18).

**Comment by MikeM2343** [comment]
Thank you!  That has fixed the problem.

**Comment by Download** [comment]
Ah great! Thanks for the feedback, it's appreciated.
