### ISSUE TITLE
The order to calling ulog.enable(...) and anylogger(...) does matter

### ISSUE THREAD

**Issue by riceyeh** [Download/ulog#49]
I find the order to calling ulog.enable(...) and anylogger(...) does matter. A logger should be defined first with anylogger('test') and then call ulog.enable('test'), otherwise it would not work. It is counter-intuitive for me. Maybe document should mention this.

Best regards, 
Rice Yeh

**Comment by Download** [comment]
@riceyeh I think I understand, but just to be sure, can you post a piece of example code?

**Comment by Download** [comment]
I cannot reproduce this with a quick test in the tutorial window.

After having lazy-loaded ulog and logged some test messages to the console, I first `ulog.enable('test')` and then I `anylogger('test').info('Testing')` and it works as expected:

```sh
Navigated to https://ulog.js.org/tutorial/
​​x test:log1                This is an ERROR message
​​! test:log1                This is a WARN message
​​x test:log2                This is an ERROR message
​​! test:log2                This is a WARN message
ulog.enable('test')
undefined
anylogger('test').info('Testing')
​i test                     Testing
undefined
anylogger('test')('Testing')
​​- test             13.12s  Testing
undefined
```

**Comment by Download** [comment]
Maybe you load `ulog` too late?
It is very good that you are creating your loggers with `anylogger('name')`. This decouples your code from `ulog`.
However, if you are using `ulog` specific features, such as `ulog.enable`, you must make sure that `ulog` is loaded before any loggers are created. This is easy to do by importing `ulog` in your entrypoint.

For example, suppose your entry point is index.js, you are doing some logging in test.js and you are calling `ulog.enable` in `config.js`. This would not work as expected:

*index.js*

```js
// first create 'test' logger
var test = require('./test')
// then configure it
require('./config')
// then call it it
test()
```` 

*test.js*

```js
// this code is decoupled from ulog
var log = require('anylogger')('test')
module.exports = function test(){
  log.info('Test') // logs nothing, as this is the anylogger no-op
  // ulog has not loaded yet
}
```

*config.js*

```js
var ulog = require('ulog')
// only here, ulog is loaded
ulog.enable('test'')
// the problem is that ulog has had no chance
// up to now to intercept calls to `anylogger`
// ulog needs to be loaded before any loggers 
// are created
```

Instead, make sure you import ulog **before** any loggers are created, by including it in your entrypoint:

*index.js*

```js
require('ulog') // <--- make sure we load ulog before creating any loggers
// further code is decoupled from ulog
// first create 'test' logger
var test = require('./test')
// then configure it
require('./config')
// then call it it
test()
```

*test.js*

```js
// this code is decoupled from ulog
var log = require('anylogger')('test')
module.exports = function test(){
  log.info('Test') // logs 'Test', because ulog is already loaded
}
```

*config.js*

```js
var ulog = require('ulog') // ulog was loaded before, this just grabs the ref
ulog.enable('test'')
// as ulog was loaded in the entry point, it was there to intercept all 
// calls to `anylogger` so all of the created loggers are governed 
// by ulog and it's configuration mechanism.
```

**Comment by Download** [comment]
@riceyeh Please re-open if this is still relevant
