### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by Messj1** [Download/ulog#54]
Hi

The benchmark of the `diary` project seem to be a little unusually since it reconfigure `ulog` every time. 
https://github.com/maraisr/diary/blob/0170945748168a5fa4b9b2927371f5d7d20bb3b5/bench/index.ts#L70-L86
```javascript
ulog() {
    let events: any[] = [];
    ulog.use([
	    {
		    outputs: {
			    custom: {
				    log(...args) {
					    events.push(args);
				    },
			    },
		    },
	    },
    ]);
    const suite = ulog('standard');
    suite.output = 'custom';
    suite.info('info message');
    return events;
}
```

I think you should make an issue that every log framework owner should write the test by himself.

> Benchmark
>   diary      x 840,954 ops/sec ±1.18% (89 runs sampled)
>   ulog       x 25,409 ops/sec ±40.24% (10 runs sampled)

As far as i know is the console log call directly mapped on the logger. So it can't be faster than a direct call. I think a good benchmark would be to see
- the memory usage of an logger object and the ulog.
- the time usage to initialize
- the performance to configure an new logger

**Comment by Download** [comment]
@Messj1 Yes well he is testing a certain scenario in which he wants to intercept log messages and store them in an array. He is setting up the configuration and then logging a message. And then runs that a whole bunch of times. Now I personally don't think that's a very realistic scenario. In fact I think you will most probably create and configure a custom output only at the very start of the program. It's not an operation I expect to perform hundreds or thousands of times. But hey maybe he has a good reason to test it that way. And yes you are right that by default, all log messages are bound directly to the console methods, or whatever underlying output, introducing the minimum amount of overhead possible. But `loglevel` does the same and I have also seen benchmarks of libraries claiming to be faster than loglevel.

In any way the guy built a great logging library from what I can see and honestly I'm honored he has mentioned me among all the greats so I got no beef with him.

**Comment by Messj1** [comment]
Was only as a hint. :wink:
